<?php

use GDO\Core\GDO_Module;

/**
 *
 */
final class Module_DogNinja extends GDO_Module
{

    public function getDependencies(): array
    {
        return [
            'Dog',
            'Net',
        ];
    }

    public function onInstall(): void
    {

        parent::onInstall(); // TODO: Change the autogenerated stub
    }


}
